kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: myclaim-1
spec:
   selector:
      matchLabels:
         type: local
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 3Gi
